// @generated
// @ts-nocheck
import '@formatjs/intl-getcanonicallocales/polyfill'
import '@formatjs/intl-locale/polyfill'
import '@formatjs/intl-enumerator/polyfill'

import '@formatjs/intl-listformat/polyfill-force'
import '@formatjs/intl-numberformat/polyfill-force'

import '@formatjs/intl-numberformat/locale-data/en'
import '@formatjs/intl-listformat/locale-data/en'

import './polyfill-force';
if (Intl.DurationFormat && typeof Intl.DurationFormat.__addLocaleData === 'function') {
  Intl.DurationFormat.__addLocaleData({"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"af-NA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"af"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"agq"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ak"}
,
{"data":{"nu":["latn","ethi"],"digitalFormat":{"separator":":"}},"locale":"am"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-AE"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-BH"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-DJ"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-DZ"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-EG"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-EH"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-ER"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-IL"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-IQ"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-JO"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-KM"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-KW"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-LB"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-LY"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-MA"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-MR"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-OM"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-PS"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-QA"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-SA"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-SD"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-SO"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-SS"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-SY"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-TD"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-TN"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar-YE"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ar"}
,
{"data":{"nu":["beng"],"digitalFormat":{"separator":":"}},"locale":"as"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"asa"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ast"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"az-Cyrl"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"az-Latn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"az"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"bas"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"be-tarask"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"be"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"bem"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"bez"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"bg"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"bm"}
,
{"data":{"nu":["beng"],"digitalFormat":{"separator":":"}},"locale":"bn-IN"}
,
{"data":{"nu":["beng"],"digitalFormat":{"separator":":"}},"locale":"bn"}
,
{"data":{"nu":["tibt"],"digitalFormat":{"separator":":"}},"locale":"bo-IN"}
,
{"data":{"nu":["tibt"],"digitalFormat":{"separator":":"}},"locale":"bo"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"br"}
,
{"data":{"nu":["deva"],"digitalFormat":{"separator":":"}},"locale":"brx"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"bs-Cyrl"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"bs-Latn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"bs"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ca-AD"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ca-ES-valencia"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ca-FR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ca-IT"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ca"}
,
{"data":{"nu":["cakm"],"digitalFormat":{"separator":":"}},"locale":"ccp-IN"}
,
{"data":{"nu":["cakm"],"digitalFormat":{"separator":":"}},"locale":"ccp"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ce"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ceb"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"cgg"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"chr"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ckb-IR"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"ckb"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"cs"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"cy"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"da-GL"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"da"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"dav"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"de-AT"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"de-BE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"de-CH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"de-IT"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"de-LI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"de-LU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"de"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"dje"}
,
{"data":{"nu":["deva"],"digitalFormat":{"separator":":"}},"locale":"doi"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"dsb"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"dua"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"dyo"}
,
{"data":{"nu":["tibt"],"digitalFormat":{"separator":":"}},"locale":"dz"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ebu"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ee-TG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ee"}
,
{"data":{"nu":["latn","grek"],"digitalFormat":{"separator":":"}},"locale":"el-CY"}
,
{"data":{"nu":["latn","grek"],"digitalFormat":{"separator":":"}},"locale":"el"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-001"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-150"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-AE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-AG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-AI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-AS"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-AT"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-AU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-BB"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-BE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-BI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-BM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-BS"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-BW"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-BZ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-CA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-CC"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-CH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-CK"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-CM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-CX"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-CY"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-DE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-DG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"en-DK"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-DM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-ER"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"en-FI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-FJ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-FK"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-FM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-GB"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-GD"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-GG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-GH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-GI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-GM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-GU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-GY"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-HK"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-IE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-IL"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-IM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-IN"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-IO"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-JE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-JM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-KE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-KI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-KN"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-KY"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-LC"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-LR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-LS"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-MG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-MH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-MO"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-MP"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-MS"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-MT"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-MU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-MW"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-MY"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-NA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-NF"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-NG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-NL"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-NR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-NU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-NZ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-PG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-PH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-PK"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-PN"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-PR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-PW"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-RW"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-SB"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-SC"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-SD"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-SE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-SG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-SH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-SI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-SL"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-SS"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-SX"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-SZ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-TC"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-TK"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-TO"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-TT"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-TV"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-TZ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-UG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-UM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-VC"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-VG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-VI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-VU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-WS"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-ZA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-ZM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en-ZW"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"en"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"eo"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-419"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-AR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-BO"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-BR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-BZ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-CL"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-CO"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-CR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-CU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-DO"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-EA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-EC"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-GQ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-GT"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-HN"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-IC"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-MX"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-NI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-PA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-PE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-PH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-PR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-PY"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-SV"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-US"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-UY"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es-VE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"es"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"et"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"eu"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ewo"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"fa-AF"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"fa"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm-BF"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm-CM"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm-GH"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm-GM"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm-GW"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm-LR"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm-MR"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm-NE"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm-NG"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm-SL"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm-SN"}
,
{"data":{"nu":["adlm"],"digitalFormat":{"separator":":"}},"locale":"ff-Adlm"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn-BF"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn-CM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn-GH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn-GM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn-GN"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn-GW"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn-LR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn-MR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn-NE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn-NG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn-SL"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff-Latn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ff"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"fi"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fil"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fo-DK"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fo"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-BE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-BF"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-BI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-BJ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-BL"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-CA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-CD"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-CF"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-CG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-CH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-CI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-CM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-DJ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-DZ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-GA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-GF"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-GN"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-GP"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-GQ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-HT"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-KM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-LU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-MA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-MC"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-MF"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-MG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-ML"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-MQ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-MR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-MU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-NC"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-NE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-PF"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-PM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-RE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-RW"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-SC"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-SN"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-SY"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-TD"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-TG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-TN"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-VU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-WF"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr-YT"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fr"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fur"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"fy"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ga-GB"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ga"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"gd"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"gl"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"gsw-FR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"gsw-LI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"gsw"}
,
{"data":{"nu":["gujr"],"digitalFormat":{"separator":":"}},"locale":"gu"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"guz"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"gv"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ha-GH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ha-NE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ha"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"haw"}
,
{"data":{"nu":["latn","hebr"],"digitalFormat":{"separator":":"}},"locale":"he"}
,
{"data":{"nu":["deva"],"digitalFormat":{"separator":":"}},"locale":"hi"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"hr-BA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"hr"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"hsb"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"hu"}
,
{"data":{"nu":["latn","armn"],"digitalFormat":{"separator":":"}},"locale":"hy"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ia"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"id"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ig"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ii"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"is"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"it-CH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"it-SM"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"it-VA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"it"}
,
{"data":{"nu":["latn","jpan","jpanfin"],"digitalFormat":{"separator":":"}},"locale":"ja"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"jgo"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"jmc"}
,
{"data":{"nu":["java"],"digitalFormat":{"separator":":"}},"locale":"jv"}
,
{"data":{"nu":["latn","geor"],"digitalFormat":{"separator":":"}},"locale":"ka"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"kab"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"kam"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"kde"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"kea"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"kgp"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"khq"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ki"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"kk"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"kkj"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"kl"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"kln"}
,
{"data":{"nu":["khmr"],"digitalFormat":{"separator":":"}},"locale":"km"}
,
{"data":{"nu":["knda"],"digitalFormat":{"separator":":"}},"locale":"kn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ko-KP"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ko"}
,
{"data":{"nu":["deva"],"digitalFormat":{"separator":":"}},"locale":"kok"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"ks-Arab"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"ks"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ksb"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ksf"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ksh"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ku"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"kw"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ky"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"lag"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"lb"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"lg"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"lkt"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ln-AO"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ln-CF"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ln-CG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ln"}
,
{"data":{"nu":["laoo"],"digitalFormat":{"separator":":"}},"locale":"lo"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"lrc-IQ"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"lrc"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"lt"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"lu"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"luo"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"luy"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"lv"}
,
{"data":{"nu":["deva"],"digitalFormat":{"separator":":"}},"locale":"mai"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mas-TZ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mas"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mer"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mfe"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mg"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mgh"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mgo"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mi"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mk"}
,
{"data":{"nu":["mlym"],"digitalFormat":{"separator":":"}},"locale":"ml"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mni-Beng"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mni"}
,
{"data":{"nu":["deva"],"digitalFormat":{"separator":":"}},"locale":"mr"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ms-BN"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"ms-ID"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ms-SG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ms"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mt"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"mua"}
,
{"data":{"nu":["mymr"],"digitalFormat":{"separator":":"}},"locale":"my"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"mzn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"naq"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nb-SJ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nb"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nd"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nds-NL"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nds"}
,
{"data":{"nu":["deva"],"digitalFormat":{"separator":":"}},"locale":"ne-IN"}
,
{"data":{"nu":["deva"],"digitalFormat":{"separator":":"}},"locale":"ne"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nl-AW"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nl-BE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nl-BQ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nl-CW"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nl-SR"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nl-SX"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nl"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nmg"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nnh"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"no"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nus"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"nyn"}
,
{"data":{"nu":["latn","ethi"],"digitalFormat":{"separator":":"}},"locale":"om-KE"}
,
{"data":{"nu":["latn","ethi"],"digitalFormat":{"separator":":"}},"locale":"om"}
,
{"data":{"nu":["orya"],"digitalFormat":{"separator":":"}},"locale":"or"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"os-RU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"os"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"pa-Arab"}
,
{"data":{"nu":["guru"],"digitalFormat":{"separator":":"}},"locale":"pa-Guru"}
,
{"data":{"nu":["guru"],"digitalFormat":{"separator":":"}},"locale":"pa"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pcm"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pl"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"ps-PK"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"ps"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt-AO"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt-CH"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt-CV"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt-GQ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt-GW"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt-LU"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt-MO"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt-MZ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt-PT"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt-ST"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt-TL"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"pt"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"qu-BO"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"qu-EC"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"qu"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"rm"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"rn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ro-MD"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ro"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"rof"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ru-BY"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ru-KG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ru-KZ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ru-MD"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ru-UA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ru"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"rw"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"rwk"}
,
{"data":{"nu":["deva"],"digitalFormat":{"separator":":"}},"locale":"sa"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sah"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"saq"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sat-Olck"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sat"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sbp"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sc"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"sd-Arab"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sd-Deva"}
,
{"data":{"nu":["arab"],"digitalFormat":{"separator":":"}},"locale":"sd"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"se-FI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"se-SE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"se"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"seh"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"ses"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sg"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"shi-Latn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"shi-Tfng"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"shi"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"si"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sk"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sl"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"smn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"so-DJ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"so-ET"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"so-KE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"so"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sq-MK"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sq-XK"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sq"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sr-Cyrl-BA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sr-Cyrl-ME"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sr-Cyrl-XK"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sr-Cyrl"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sr-Latn-BA"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sr-Latn-ME"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sr-Latn-XK"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sr-Latn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sr"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"su-Latn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"su"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sv-AX"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":"."}},"locale":"sv-FI"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sv"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sw-CD"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sw-KE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sw-UG"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"sw"}
,
{"data":{"nu":["tamldec","taml"],"digitalFormat":{"separator":":"}},"locale":"ta-LK"}
,
{"data":{"nu":["tamldec","taml"],"digitalFormat":{"separator":":"}},"locale":"ta-MY"}
,
{"data":{"nu":["tamldec","taml"],"digitalFormat":{"separator":":"}},"locale":"ta-SG"}
,
{"data":{"nu":["tamldec","taml"],"digitalFormat":{"separator":":"}},"locale":"ta"}
,
{"data":{"nu":["telu"],"digitalFormat":{"separator":":"}},"locale":"te"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"teo-KE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"teo"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"tg"}
,
{"data":{"nu":["thai"],"digitalFormat":{"separator":":"}},"locale":"th"}
,
{"data":{"nu":["latn","ethi"],"digitalFormat":{"separator":":"}},"locale":"ti-ER"}
,
{"data":{"nu":["latn","ethi"],"digitalFormat":{"separator":":"}},"locale":"ti"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"tk"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"to"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"tr-CY"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"tr"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"tt"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"twq"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"tzm"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"ug"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"uk"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"und"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":"٫"}},"locale":"ur-IN"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"ur"}
,
{"data":{"nu":["arabext"],"digitalFormat":{"separator":":"}},"locale":"uz-Arab"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"uz-Cyrl"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"uz-Latn"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"uz"}
,
{"data":{"nu":["vaii"],"digitalFormat":{"separator":":"}},"locale":"vai-Latn"}
,
{"data":{"nu":["vaii"],"digitalFormat":{"separator":":"}},"locale":"vai-Vaii"}
,
{"data":{"nu":["vaii"],"digitalFormat":{"separator":":"}},"locale":"vai"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"vi"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"vun"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"wae"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"wo"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"xh"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"xog"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"yav"}
,
{"data":{"nu":["latn","hebr"],"digitalFormat":{"separator":":"}},"locale":"yi"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"yo-BJ"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"yo"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"yrl-CO"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"yrl-VE"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"yrl"}
,
{"data":{"nu":["hanidec","hans","hansfin"],"digitalFormat":{"separator":":"}},"locale":"yue-Hans"}
,
{"data":{"nu":["hanidec","hant","hantfin"],"digitalFormat":{"separator":":"}},"locale":"yue-Hant"}
,
{"data":{"nu":["hanidec","hant","hantfin"],"digitalFormat":{"separator":":"}},"locale":"yue"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"zgh"}
,
{"data":{"nu":["hanidec","hans","hansfin"],"digitalFormat":{"separator":":"}},"locale":"zh-Hans-HK"}
,
{"data":{"nu":["hanidec","hans","hansfin"],"digitalFormat":{"separator":":"}},"locale":"zh-Hans-MO"}
,
{"data":{"nu":["hanidec","hans","hansfin"],"digitalFormat":{"separator":":"}},"locale":"zh-Hans-SG"}
,
{"data":{"nu":["hanidec","hans","hansfin"],"digitalFormat":{"separator":":"}},"locale":"zh-Hans"}
,
{"data":{"nu":["hanidec","hant","hantfin"],"digitalFormat":{"separator":":"}},"locale":"zh-Hant-HK"}
,
{"data":{"nu":["hanidec","hant","hantfin"],"digitalFormat":{"separator":":"}},"locale":"zh-Hant-MO"}
,
{"data":{"nu":["hanidec","hant","hantfin"],"digitalFormat":{"separator":":"}},"locale":"zh-Hant"}
,
{"data":{"nu":["hanidec","hans","hansfin"],"digitalFormat":{"separator":":"}},"locale":"zh"}
,
{"data":{"nu":["latn"],"digitalFormat":{"separator":":"}},"locale":"zu"}
)
}