packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  - "packages/*/integration-tests"
  - "packages/*/examples"
  - "packages/*/benchmark"
  - "website"
  - "!packages/editor"
