"""Generate Python wrappers and readonly argument stubs from a source catalog."""

from __future__ import annotations

import argparse
import json
import keyword
import re
from collections.abc import Mapping
from pathlib import Path

from intl._native import _message_arguments

_TYPES = {
    "value": {"str", "bool", "int", "float", "date", "datetime", "None"},
    "number": {"int", "float"},
    "datetime": {"int", "float", "date", "datetime"},
    "select": {"str", "bool", "int", "float", "None"},
}
_ORDER = ("str", "bool", "int", "float", "date", "datetime", "None")


def _function_name(message_id: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9_]", "_", message_id)
    if not name or name[0].isdigit():
        name = "message_" + name
    if keyword.iskeyword(name) or name.startswith("_"):
        name = "message_" + name
    return name


def generate(catalog: Mapping[str, str | Mapping[str, object]]) -> tuple[str, str]:
    """Return .py and .pyi text. Reject invalid ICU, name collisions, and rich tags."""
    implementation = [
        "# Generated by python -m intl.codegen. Do not edit.",
        "from collections.abc import Mapping as _Mapping",
        "from intl import Intl as _Intl, MessageValue as _MessageValue",
        "",
    ]
    declarations = [
        "# Generated by python -m intl.codegen. Do not edit.",
        "from datetime import date, datetime",
        "from typing import TypedDict",
        "from typing_extensions import ReadOnly",
        "from intl import Intl as _Intl",
        "",
    ]
    names: set[str] = set()
    for message_id, entry in sorted(catalog.items()):
        if not isinstance(message_id, str):
            raise ValueError("Catalog IDs must be strings")
        if isinstance(entry, str):
            message, description = entry, None
        elif isinstance(entry, Mapping):
            message = entry.get("defaultMessage")
            description = entry.get("description")
        else:
            raise ValueError(f"{message_id}: expected a string or message descriptor")
        if not isinstance(message, str):
            raise ValueError(f"{message_id}: defaultMessage must be a string")
        if description is not None and not isinstance(description, str):
            raise ValueError(f"{message_id}: description must be a string")
        function = _function_name(message_id)
        if function in names or function in {"date", "datetime", "TypedDict", "ReadOnly", "str", "bool", "int", "float"}:
            raise ValueError(f"{message_id}: generated name collision: {function}")
        names.add(function)
        try:
            arguments = _message_arguments(message)
        except ValueError as error:
            raise ValueError(f"{message_id}: {error}") from error
        fields = []
        for name, kinds in sorted(arguments.items()):
            if "tag" in kinds:
                raise ValueError(f"{message_id}: rich tag {name!r} is unsupported by Python Intl")
            allowed = set(_ORDER)
            for kind in kinds:
                allowed &= _TYPES[kind]
            if not allowed:
                raise ValueError(f"{message_id}: incompatible ICU roles for {name!r}")
            value_type = " | ".join(t for t in _ORDER if t in allowed)
            fields.append(f"{name!r}: ReadOnly[{value_type}]")
        values_type = f"_{function}Values"
        declarations.append(f"{values_type} = TypedDict({values_type!r}, {{{', '.join(fields)}}})")
        optional = " | None = None" if not fields else ""
        declarations.append(f"def {function}(intl: _Intl, *, values: {values_type}{optional}) -> str: ...")
        declarations.append("")
        implementation.append(
            f"def {function}(intl: _Intl, *, values: _Mapping[str, _MessageValue]{optional}) -> str:"
        )
        implementation.append(
            f"    return intl.format_message(id={message_id!r}, default_message={message!r}, "
            f"description={description!r}, values=values)"
        )
        implementation.append("")
    return "\n".join(implementation), "\n".join(declarations)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("catalog", type=Path, help="FormatJS source catalog JSON")
    parser.add_argument("--out", type=Path, required=True, help="Output .py module; a sibling .pyi is also written")
    args = parser.parse_args()
    if args.out.suffix != ".py":
        parser.error("--out must end in .py")
    catalog = json.loads(args.catalog.read_text(encoding="utf-8"))
    if not isinstance(catalog, dict):
        parser.error("catalog must be a JSON object")
    try:
        implementation, declarations = generate(catalog)
    except ValueError as error:
        parser.error(str(error))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(implementation, encoding="utf-8")
    args.out.with_suffix(".pyi").write_text(declarations, encoding="utf-8")


if __name__ == "__main__":
    main()
