# load("@npm//:@napi-rs/cli/package_json.bzl", napi_bin = "bin")
# load("@crate_index//:defs.bzl", "all_crate_deps")

# TODO: fix this
# napi_bin.napi(
#     name = "swc-formatjs-custom-transform",
#     args = ["build", "--platform"],
#     outs = [
#         # TODO: build on other platforms
#         "swc.darwin-arm64.node"
#     ],
#     srcs = glob(["src/**/*.rs"]) + [
#         "build.rs",
#         "Cargo.toml",
#         "package.json",
#     ] + all_crate_deps(
#         normal = True,
#         proc_macro = True,
#     ),
#     tags = ["manual"]
# )
