/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OptionsSchema {
  moduleSourceName?: string;
  overrideIdFn?: (id?: string, defaultMessage?: string, description?: string, filePath?: string) => string;
  idInterpolationPattern?: string;
  removeDefaultMessage?: boolean;
  additionalComponentNames?: string[];
  pragma?: string;
  extractFromFormatMessageCall?: boolean;
  extractSourceLocation?: boolean;
}
