load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")
load("@rules_rust//rust:defs.bzl", "rust_doc_test")

exports_files(
    [
        "Cargo.toml",
        "README.md",
        "lib.rs",
        "provider_tests.rs",
        "formatted_message.rs",
        "argument_types.rs",
    ],
    visibility = ["//visibility:public"],
)

rust_library(
    name = "formatjs_intl",
    srcs = [
        "argument_types.rs",
        "formatted_message.rs",
        "lib.rs",
        "provider_tests.rs",
    ],
    crate_features = ["compiled_data"],
    crate_name = "formatjs_intl",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/formatjs_intl_macros",
        "//crates/icu_messageformat",
        "@crates//:icu_locale",
        "@crates//:icu_provider",
        "@crates//:icu_provider_adapters",
    ],
)

rust_test(
    name = "formatjs_intl_test",
    size = "small",
    crate = ":formatjs_intl",
    crate_features = ["compiled_data"],
    deps = [
        "@crates//:icu",
        "@crates//:serde_json",
    ],
)

rust_doc_test(
    name = "formatjs_intl_doc_test",
    size = "small",
    crate = ":formatjs_intl",
    crate_features = ["compiled_data"],
)

rust_library(
    name = "without_compiled_data",
    testonly = True,
    srcs = [
        "argument_types.rs",
        "formatted_message.rs",
        "lib.rs",
        "provider_tests.rs",
    ],
    crate_name = "formatjs_intl",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/formatjs_intl_macros",
        "//crates/icu_messageformat:without_compiled_data",
        "@crates//:icu_locale",
        "@crates//:icu_provider",
        "@crates//:icu_provider_adapters",
    ],
)

rust_test(
    name = "provider_test",
    size = "small",
    crate = ":without_compiled_data",
    deps = ["@crates//:icu"],
)
