[package]
name = "formatjs_intl"
version = "2.0.0"
edition = "2024"
authors = ["FormatJS Team", "Long Ho <holevietlong@gmail.com>"]
description = "High-level internationalization runtime for Rust"
license = "BSD-3-Clause"
repository = "https://github.com/formatjs/formatjs"
homepage = "https://formatjs.io/"
documentation = "https://docs.rs/formatjs_intl"
keywords = ["icu", "i18n", "internationalization", "localization", "intl"]
categories = ["internationalization", "localization"]
readme = "README.md"
rust-version = "1.92"

[features]
default = ["compiled_data"]
compiled_data = [
  "icu_locale/default",
  "formatjs_icu_messageformat/compiled_data",
]

[dependencies]
formatjs_icu_messageformat = { path = "../icu_messageformat", version = "0.1.4", default-features = false }
formatjs_intl_macros = { path = "../formatjs_intl_macros", version = "1.0.0" }
icu_locale = { version = "2.1", default-features = false, features = ["serde"] }
icu_provider = { version = "2.1", features = ["sync"] }

[lib]
path = "lib.rs"
crate-type = ["rlib"]

[dev-dependencies]
icu = { version = "2.1", default-features = false }
icu_provider = { version = "2.1", features = ["deserialize_json"] }
serde_json = "1.0"
