import {ummAlQura} from '@formatjs_generated/icu.calendar/umm-al-qura.js'
import civil from '#packages/ecma402-abstract/DateTimeFormat/calendars/islamic-civil.js'
import type {CalendarData} from '#packages/ecma402-abstract/DateTimeFormat/CalendarDateFromTime.js'

// Decode pinned ICU4X month lengths generated by
// packages/intl-datetimeformat/scripts/calendar-data/umm_al_qura.rs.
// This is calendar data used by ToLocalTime, not an ECMA-402 table encoding.
// https://tc39.es/ecma402/#sec-tolocaltime
const data: CalendarData = {
  calendar: 'islamic-umalqura',
  dateFromTime(t) {
    const epochDay = Math.floor(t / 86400000)
    const {startDays, firstYear, monthLengths} = ummAlQura
    if (
      epochDay >= startDays[0] &&
      epochDay < startDays[startDays.length - 1]
    ) {
      let low = 0
      let high = startDays.length - 1
      while (low + 1 < high) {
        const middle = Math.floor((low + high) / 2)
        if (startDays[middle] <= epochDay) low = middle
        else high = middle
      }
      let dayOfYear = epochDay - startDays[low]
      let month = 0
      const packed = monthLengths[low]
      while (dayOfYear >= 29 + ((packed >>> month) & 1)) {
        dayOfYear -= 29 + ((packed >>> month) & 1)
        month++
      }
      return {era: '0', year: firstYear + low, month, day: dayOfYear + 1}
    }
    // ICU4X uses the civil calendar outside its official Umm al-Qura table.
    return civil.dateFromTime(t)
  },
}

export default data
