import {basename} from 'node:path'
import {readdirSync, readFileSync, statSync} from 'node:fs'
import {outputFileSync} from 'fs-extra/esm'
import minimist from 'minimist'
import {
  parseLDMLCollations,
  type CollationRule,
  type ParsedLDMLCollation,
} from './parse-ldml-collation.js'

type PackedSetting = readonly [
  type: 'setting',
  key: string,
  value: string | readonly string[],
]

type PackedReset =
  | readonly [type: 'reset', value: string]
  | readonly [type: 'reset', value: string, before: 1 | 2 | 3]

type PackedRelation =
  | readonly [type: 'relation', strength: string, value: string]
  | readonly [
      type: 'relation',
      strength: string,
      value: string,
      expansion: string | undefined,
      prefix: string | undefined,
    ]

type PackedRule = PackedSetting | PackedReset | PackedRelation

type PackedCollation = {
  readonly alias?: string
  readonly rules?: readonly PackedRule[]
}

const UNDERSCORE_RE = /_/g
const WHITESPACE_RE = /\s+/g

// Packs LDML collation tailorings into generated data consumed by runtime
// CompareStrings. The XML/rule parser follows LDML Part 5 Collation.
// https://www.unicode.org/reports/tr35/tr35-collation.html#Collation_Tailorings

function collationPaths(dir: string): string[] {
  const entries = readdirSync(dir).flatMap(entry => {
    const path = `${dir}/${entry}`
    return statSync(path).isDirectory() ? collationPaths(path) : [path]
  })
  return entries.filter(path => path.endsWith('.xml')).sort()
}

function collationPathList(input: string | string[] | undefined): string[] {
  if (Array.isArray(input)) {
    return input.filter(path => path.endsWith('.xml')).sort()
  }
  return (input || '')
    .split(WHITESPACE_RE)
    .filter(path => path.endsWith('.xml'))
    .sort()
}

function localeFromPath(path: string): string {
  return basename(path, '.xml').replace(UNDERSCORE_RE, '-')
}

function packRule(rule: CollationRule): PackedRule {
  // Preserve LDML reset/relation/setting order. Runtime compilation applies
  // each reset chain in sequence against root UCA weights.
  // https://www.unicode.org/reports/tr35/tr35-collation.html#Orderings
  switch (rule.type) {
    case 'reset':
      return rule.before
        ? ['reset', rule.value, rule.before]
        : ['reset', rule.value]
    case 'relation':
      return rule.expansion !== undefined || rule.prefix !== undefined
        ? ['relation', rule.strength, rule.value, rule.expansion, rule.prefix]
        : ['relation', rule.strength, rule.value]
    case 'unknown':
      return ['setting', rule.key, rule.value]
    default:
      return ['setting', rule.type, rule.value]
  }
}

function packCollation(collation: ParsedLDMLCollation): PackedCollation {
  if (collation.alias) {
    // LDML aliases redirect one locale/type collation to another.
    // https://www.unicode.org/reports/tr35/tr35-collation.html#Collation_Types
    return {alias: collation.alias}
  }
  return {rules: collation.rules.map(packRule)}
}

function serialize(value: unknown): string {
  return JSON.stringify(value)
}

const argv = minimist(process.argv.slice(2), {
  string: ['collationDir', 'collationPath', 'collationPaths', 'out'],
})

if (!argv.collationDir && !argv.collationPath && !argv.collationPaths) {
  throw new Error(
    '--collationDir, --collationPath, or --collationPaths is required'
  )
}
if (!argv.out) {
  throw new Error('--out is required')
}

const paths =
  argv.collationPath !== undefined
    ? collationPathList(argv.collationPath)
    : argv.collationPaths === undefined
      ? collationPaths(argv.collationDir)
      : collationPathList(argv.collationPaths)

const tailorings: Record<string, Record<string, PackedCollation>> = {}

for (const path of paths) {
  const locale = localeFromPath(path)
  const source = readFileSync(path, 'utf8')
  for (const collation of parseLDMLCollations(locale, source)) {
    if (!collation.alias && collation.rules.length === 0) {
      continue
    }
    const localeTailorings = (tailorings[locale] ||= {})
    localeTailorings[collation.type] = packCollation(collation)
  }
}

outputFileSync(
  argv.out,
  `// @generated by packages/intl-collator/scripts/generate-tailoring-data.ts
// CLDR locale tailoring rules generated from common/collation/*.xml.

export type PackedLDMLSetting = readonly [
  type: 'setting',
  key: string,
  value: string | readonly string[],
]

export type PackedLDMLReset =
  | readonly [type: 'reset', value: string]
  | readonly [type: 'reset', value: string, before: 1 | 2 | 3]

export type PackedLDMLRelation =
  | readonly [type: 'relation', strength: string, value: string]
  | readonly [
      type: 'relation',
      strength: string,
      value: string,
      expansion: string | undefined,
      prefix: string | undefined,
    ]

export type PackedLDMLRule =
  | PackedLDMLSetting
  | PackedLDMLReset
  | PackedLDMLRelation

export type PackedLDMLCollation = {
  readonly alias?: string
  readonly rules?: readonly PackedLDMLRule[]
}

export const collationTailorings = ${serialize(tailorings)} as const
`
)
