import minimist from 'minimist'
import {readFileSync} from 'node:fs'
import {outputFileSync} from 'fs-extra/esm'
import {
  buildUCATrie,
  parseUCA,
  type PackedTrieNode,
  type ParsedUCAEntry,
} from './parse-uca.ts'

type PackedElement = readonly [
  primary: number,
  secondary: number,
  tertiary: number,
  quaternary: number,
  flags: number,
]

function packElement(entry: ParsedUCAEntry): PackedElement[] {
  return entry.elements.map(element => [
    element.primary,
    element.secondary,
    element.tertiary,
    element.quaternary,
    element.variable ? 1 : 0,
  ])
}

function countTrieNodes(node: PackedTrieNode): number {
  let count = 1
  if (node.next) {
    for (const key of Object.keys(node.next)) {
      count += countTrieNodes(node.next[Number(key)])
    }
  }
  return count
}

function serialize(value: unknown): string {
  return JSON.stringify(value)
}

const argv = minimist(process.argv.slice(2), {
  string: ['ucaPath', 'out'],
})

if (!argv.ucaPath) {
  throw new Error('--ucaPath is required')
}
if (!argv.out) {
  throw new Error('--out is required')
}

const source = readFileSync(argv.ucaPath, 'utf8')
const entries = parseUCA(source)
const rootTrie = buildUCATrie(entries)
const rootElements = entries.map(packElement)

outputFileSync(
  argv.out,
  `// @generated by packages/intl-collator/scripts/generate-root-data.ts
// CLDR root collation data generated from FractionalUCA_SHORT.txt.

export type PackedCollationElement = readonly [
  primary: number,
  secondary: number,
  tertiary: number,
  quaternary: number,
  flags: number,
]

export type PackedTrieNode = {
  value?: number
  next?: Record<number, PackedTrieNode>
}

export const rootTrie: PackedTrieNode = ${serialize(rootTrie)}

export const rootElements: readonly (readonly PackedCollationElement[])[] = ${serialize(rootElements)}

export const rootDataStats = {
  entries: ${entries.length},
  trieNodes: ${countTrieNodes(rootTrie)},
} as const
`
)
