import {basename} from 'node:path'
import minimist from 'minimist'
import {readdirSync, readFileSync, statSync} from 'node:fs'
import {outputFileSync} from 'fs-extra/esm'
import {parseLDMLCollations} from './parse-ldml-collation.ts'

type GeneratedLocaleData = {
  readonly co: readonly string[]
  readonly kn: readonly ['false', 'true']
  readonly kf: readonly ['false', 'upper', 'lower']
  readonly sensitivity: 'variant'
  readonly ignorePunctuation: false
}

const DEFAULT_COLLATION_RE = /<defaultCollation\b[^>]*>([^<]+)<\/defaultCollation>/i

function collationPaths(dir: string): string[] {
  const entries = readdirSync(dir).flatMap(entry => {
    const path = `${dir}/${entry}`
    return statSync(path).isDirectory() ? collationPaths(path) : [path]
  })
  return entries.filter(path => path.endsWith('.xml')).sort()
}

function collationPathList(input: string | string[] | undefined): string[] {
  return (Array.isArray(input) ? input.join(' ') : input || '')
    .split(/\s+/)
    .filter(path => path.endsWith('.xml'))
    .sort()
}

function collationPathsFromCopyConfig(dir: string): string[] {
  const configPath = `${dir}_config.json`
  const config = JSON.parse(readFileSync(configPath, 'utf8')) as {
    files: Array<{path: string}>
  }
  return config.files.map(file => file.path).filter(path => path.endsWith('.xml')).sort()
}

function localeFromPath(path: string): string {
  return basename(path, '.xml').replace(/_/g, '-')
}

function defaultCollation(source: string): string {
  return DEFAULT_COLLATION_RE.exec(source)?.[1].trim() || 'standard'
}

function serialize(value: unknown): string {
  return JSON.stringify(value)
}

const argv = minimist(process.argv.slice(2), {
  string: ['collationDir', 'collationPath', 'collationPaths', 'out'],
})

if (!argv.collationDir && !argv.collationPath && !argv.collationPaths) {
  throw new Error('--collationDir, --collationPath, or --collationPaths is required')
}
if (!argv.out) {
  throw new Error('--out is required')
}

const localeData: Record<string, GeneratedLocaleData> = {}

const paths =
  argv.collationPath !== undefined
    ? collationPathList(argv.collationPath)
    : argv.collationPaths === undefined
    ? collationPaths(argv.collationDir)
    : collationPathList(argv.collationPaths)
const resolvedPaths =
  paths.length === 0 && argv.collationDir
    ? collationPathsFromCopyConfig(argv.collationDir)
    : paths

for (const path of resolvedPaths) {
  const source = readFileSync(path, 'utf8')
  const locale = localeFromPath(path)
  const defaultType = defaultCollation(source)
  const collations = parseLDMLCollations(locale, source)
  const collationTypes = new Set<string>(['default'])
  for (const collation of collations) {
    if (
      collation.type !== 'standard' &&
      collation.type !== 'search' &&
      collation.type !== defaultType
    ) {
      collationTypes.add(collation.type)
    }
  }
  if (defaultType !== 'standard' && defaultType !== 'search') {
    collationTypes.add(defaultType)
  }
  localeData[locale] = {
    co: [...collationTypes].sort(),
    kn: ['false', 'true'],
    kf: ['false', 'upper', 'lower'],
    sensitivity: 'variant',
    ignorePunctuation: false,
  }
}

const availableLocales = Object.keys(localeData).sort()

outputFileSync(
  argv.out,
  `// @generated by packages/intl-collator/scripts/generate-locale-data.ts
// CLDR locale collation metadata generated from common/collation/*.xml.

export const availableCollationLocales = ${serialize(availableLocales)} as const

export const collationLocaleData = ${serialize(localeData)} as const
`
)
