import minimist from 'minimist'
import {readFileSync} from 'node:fs'
import {outputFileSync} from 'fs-extra/esm'
import {
  buildUCATrie,
  parseUCA,
  parseUCAVariableTop,
  type PackedTrieNode,
  type ParsedUCAEntry,
} from './parse-uca.js'

type PackedElement = readonly [
  primary: number,
  secondary: number,
  tertiary: number,
  quaternary: number,
  flags: number,
]

type PackedPrefixEntry = {
  readonly prefix: readonly number[]
  readonly codePoints: readonly number[]
  readonly elements: readonly PackedElement[]
}

function packElement(
  entry: ParsedUCAEntry,
  variableTop: number | undefined
): PackedElement[] {
  // UCA elements carry comparison weights by level. The flags slot marks
  // variable elements so alternate shifted / ignorePunctuation can filter them.
  // https://www.unicode.org/reports/tr10/#Multi_Level_Comparison
  // https://www.unicode.org/reports/tr10/#Variable_Weighting
  return entry.elements.map(element => [
    element.primary,
    element.secondary,
    element.tertiary,
    element.quaternary,
    element.variable ||
    (variableTop !== undefined &&
      element.primary > 0 &&
      element.primary <= variableTop)
      ? 1
      : 0,
  ])
}

function countTrieNodes(node: PackedTrieNode): number {
  let count = 1
  if (node.next) {
    for (const key of Object.keys(node.next)) {
      count += countTrieNodes(node.next[Number(key)])
    }
  }
  return count
}

function serialize(value: unknown): string {
  return JSON.stringify(value)
}

const argv = minimist(process.argv.slice(2), {
  string: ['ucaPath', 'out'],
})

if (!argv.ucaPath) {
  throw new Error('--ucaPath is required')
}
if (!argv.out) {
  throw new Error('--out is required')
}

const source = readFileSync(argv.ucaPath, 'utf8')
const entries = parseUCA(source)
const variableTop = parseUCAVariableTop(source)
// UCA root mappings without prefixes go into the longest-match trie; prefixed
// mappings are emitted separately for context-sensitive lookup.
// https://www.unicode.org/reports/tr10/#Contractions
// https://www.unicode.org/reports/tr10/#Contextual_Sensitive_Mappings
const rootEntries = entries.filter(entry => entry.prefix === undefined)
const prefixEntries = entries.filter(
  (entry): entry is ParsedUCAEntry & {prefix: number[]} =>
    entry.prefix !== undefined
)
const rootTrie = buildUCATrie(rootEntries)
const rootElements = rootEntries.map(entry => packElement(entry, variableTop))
const rootPrefixEntries: PackedPrefixEntry[] = prefixEntries.map(entry => ({
  prefix: entry.prefix,
  codePoints: entry.codePoints,
  elements: packElement(entry, variableTop),
}))

outputFileSync(
  argv.out,
  `// @generated by packages/intl-collator/scripts/generate-root-data.ts
// CLDR root collation data generated from FractionalUCA_SHORT.txt.

export type PackedCollationElement = readonly [
  primary: number,
  secondary: number,
  tertiary: number,
  quaternary: number,
  flags: number,
]

export type PackedTrieNode = {
  value?: number
  next?: Record<number, PackedTrieNode>
}

export type PackedPrefixEntry = {
  readonly prefix: readonly number[]
  readonly codePoints: readonly number[]
  readonly elements: readonly PackedCollationElement[]
}

export const rootTrie: PackedTrieNode = ${serialize(rootTrie)}

export const rootElements: readonly (readonly PackedCollationElement[])[] = ${serialize(rootElements)}

export const rootPrefixEntries: readonly PackedPrefixEntry[] = ${serialize(rootPrefixEntries)}

export const rootDataStats = {
  entries: ${rootEntries.length},
  prefixEntries: ${prefixEntries.length},
  trieNodes: ${countTrieNodes(rootTrie)},
  variableTop: ${variableTop ?? 'undefined'},
} as const
`
)
