// @generated from time-data-gen.ts
use once_cell::sync::Lazy;
use std::collections::HashMap;

/// Time format preferences by locale
pub static TIME_DATA: Lazy<HashMap<String, Vec<&'static str>>> = Lazy::new(|| {
    HashMap::from([
        ("419".to_string(), vec!["h", "H", "hB", "hb"]),
        ("AX".to_string(), vec!["H"]),
        ("BQ".to_string(), vec!["H"]),
        ("CP".to_string(), vec!["H"]),
        ("CZ".to_string(), vec!["H"]),
        ("DK".to_string(), vec!["H"]),
        ("FI".to_string(), vec!["H"]),
        ("ID".to_string(), vec!["H"]),
        ("IS".to_string(), vec!["H"]),
        ("ML".to_string(), vec!["H"]),
        ("NE".to_string(), vec!["H"]),
        ("RU".to_string(), vec!["H"]),
        ("SE".to_string(), vec!["H"]),
        ("SJ".to_string(), vec!["H"]),
        ("SK".to_string(), vec!["H"]),
        ("AS".to_string(), vec!["h", "H"]),
        ("BT".to_string(), vec!["h", "H"]),
        ("DJ".to_string(), vec!["h", "H"]),
        ("ER".to_string(), vec!["h", "H"]),
        ("GH".to_string(), vec!["h", "H"]),
        ("IN".to_string(), vec!["h", "H"]),
        ("LS".to_string(), vec!["h", "H"]),
        ("PG".to_string(), vec!["h", "H"]),
        ("PW".to_string(), vec!["h", "H"]),
        ("SO".to_string(), vec!["h", "H"]),
        ("TO".to_string(), vec!["h", "H"]),
        ("VU".to_string(), vec!["h", "H"]),
        ("WS".to_string(), vec!["h", "H"]),
        ("001".to_string(), vec!["H", "h"]),
        ("BI".to_string(), vec!["H", "h"]),
        ("BY".to_string(), vec!["H", "h"]),
        ("FO".to_string(), vec!["H", "h"]),
        ("GL".to_string(), vec!["H", "h"]),
        ("HU".to_string(), vec!["H", "h"]),
        ("MG".to_string(), vec!["H", "h"]),
        ("MT".to_string(), vec!["H", "h"]),
        ("MU".to_string(), vec!["H", "h"]),
        ("MV".to_string(), vec!["H", "h"]),
        ("NO".to_string(), vec!["H", "h"]),
        ("PL".to_string(), vec!["H", "h"]),
        ("RW".to_string(), vec!["H", "h"]),
        ("TH".to_string(), vec!["H", "h"]),
        ("TJ".to_string(), vec!["H", "h"]),
        ("TM".to_string(), vec!["H", "h"]),
        ("VN".to_string(), vec!["H", "h"]),
        ("ZW".to_string(), vec!["H", "h"]),
        ("AL".to_string(), vec!["h", "H", "hB"]),
        ("TD".to_string(), vec!["h", "H", "hB"]),
        ("ca-ES".to_string(), vec!["H", "h", "hB"]),
        ("CF".to_string(), vec!["H", "h", "hB"]),
        ("CM".to_string(), vec!["H", "h", "hB"]),
        ("fr-CA".to_string(), vec!["H", "h", "hB"]),
        ("gl-ES".to_string(), vec!["H", "h", "hB"]),
        ("it-CH".to_string(), vec!["H", "h", "hB"]),
        ("it-IT".to_string(), vec!["H", "h", "hB"]),
        ("LU".to_string(), vec!["H", "h", "hB"]),
        ("NP".to_string(), vec!["H", "h", "hB"]),
        ("PF".to_string(), vec!["H", "h", "hB"]),
        ("SC".to_string(), vec!["H", "h", "hB"]),
        ("SM".to_string(), vec!["H", "h", "hB"]),
        ("SN".to_string(), vec!["H", "h", "hB"]),
        ("TF".to_string(), vec!["H", "h", "hB"]),
        ("VA".to_string(), vec!["H", "h", "hB"]),
        ("CY".to_string(), vec!["h", "H", "hb", "hB"]),
        ("GR".to_string(), vec!["h", "H", "hb", "hB"]),
        ("AR".to_string(), vec!["h", "H", "hB", "hb"]),
        ("BO".to_string(), vec!["h", "H", "hB", "hb"]),
        ("CL".to_string(), vec!["h", "H", "hB", "hb"]),
        ("CO".to_string(), vec!["h", "H", "hB", "hb"]),
        ("CR".to_string(), vec!["h", "H", "hB", "hb"]),
        ("CU".to_string(), vec!["h", "H", "hB", "hb"]),
        ("DO".to_string(), vec!["h", "H", "hB", "hb"]),
        ("EC".to_string(), vec!["h", "H", "hB", "hb"]),
        ("GT".to_string(), vec!["h", "H", "hB", "hb"]),
        ("HN".to_string(), vec!["h", "H", "hB", "hb"]),
        ("KP".to_string(), vec!["h", "H", "hB", "hb"]),
        ("KR".to_string(), vec!["h", "H", "hB", "hb"]),
        ("MX".to_string(), vec!["h", "H", "hB", "hb"]),
        ("NA".to_string(), vec!["h", "H", "hB", "hb"]),
        ("NI".to_string(), vec!["h", "H", "hB", "hb"]),
        ("PA".to_string(), vec!["h", "H", "hB", "hb"]),
        ("PE".to_string(), vec!["h", "H", "hB", "hb"]),
        ("PR".to_string(), vec!["h", "H", "hB", "hb"]),
        ("PY".to_string(), vec!["h", "H", "hB", "hb"]),
        ("SV".to_string(), vec!["h", "H", "hB", "hb"]),
        ("UY".to_string(), vec!["h", "H", "hB", "hb"]),
        ("VE".to_string(), vec!["h", "H", "hB", "hb"]),
        ("AC".to_string(), vec!["H", "h", "hb", "hB"]),
        ("AI".to_string(), vec!["H", "h", "hb", "hB"]),
        ("BW".to_string(), vec!["H", "h", "hb", "hB"]),
        ("BZ".to_string(), vec!["H", "h", "hb", "hB"]),
        ("CC".to_string(), vec!["H", "h", "hb", "hB"]),
        ("CK".to_string(), vec!["H", "h", "hb", "hB"]),
        ("CX".to_string(), vec!["H", "h", "hb", "hB"]),
        ("DG".to_string(), vec!["H", "h", "hb", "hB"]),
        ("en-IL".to_string(), vec!["H", "h", "hb", "hB"]),
        ("FK".to_string(), vec!["H", "h", "hb", "hB"]),
        ("GB".to_string(), vec!["H", "h", "hb", "hB"]),
        ("GG".to_string(), vec!["H", "h", "hb", "hB"]),
        ("GI".to_string(), vec!["H", "h", "hb", "hB"]),
        ("IE".to_string(), vec!["H", "h", "hb", "hB"]),
        ("IM".to_string(), vec!["H", "h", "hb", "hB"]),
        ("IO".to_string(), vec!["H", "h", "hb", "hB"]),
        ("JE".to_string(), vec!["H", "h", "hb", "hB"]),
        ("LT".to_string(), vec!["H", "h", "hb", "hB"]),
        ("MK".to_string(), vec!["H", "h", "hb", "hB"]),
        ("MN".to_string(), vec!["H", "h", "hb", "hB"]),
        ("MS".to_string(), vec!["H", "h", "hb", "hB"]),
        ("NF".to_string(), vec!["H", "h", "hb", "hB"]),
        ("NG".to_string(), vec!["H", "h", "hb", "hB"]),
        ("NR".to_string(), vec!["H", "h", "hb", "hB"]),
        ("NU".to_string(), vec!["H", "h", "hb", "hB"]),
        ("PN".to_string(), vec!["H", "h", "hb", "hB"]),
        ("SH".to_string(), vec!["H", "h", "hb", "hB"]),
        ("SX".to_string(), vec!["H", "h", "hb", "hB"]),
        ("TA".to_string(), vec!["H", "h", "hb", "hB"]),
        ("ZA".to_string(), vec!["H", "h", "hb", "hB"]),
        ("af-ZA".to_string(), vec!["H", "h", "hB", "hb"]),
        ("EA".to_string(), vec!["H", "h", "hB", "hb"]),
        ("es-BR".to_string(), vec!["H", "h", "hB", "hb"]),
        ("es-ES".to_string(), vec!["H", "h", "hB", "hb"]),
        ("es-GQ".to_string(), vec!["H", "h", "hB", "hb"]),
        ("IC".to_string(), vec!["H", "h", "hB", "hb"]),
        ("KG".to_string(), vec!["H", "h", "hB", "hb"]),
        ("KM".to_string(), vec!["H", "h", "hB", "hb"]),
        ("LK".to_string(), vec!["H", "h", "hB", "hb"]),
        ("MA".to_string(), vec!["H", "h", "hB", "hb"]),
        ("AD".to_string(), vec!["H", "hB"]),
        ("AM".to_string(), vec!["H", "hB"]),
        ("AO".to_string(), vec!["H", "hB"]),
        ("AT".to_string(), vec!["H", "hB"]),
        ("AW".to_string(), vec!["H", "hB"]),
        ("BE".to_string(), vec!["H", "hB"]),
        ("BF".to_string(), vec!["H", "hB"]),
        ("BJ".to_string(), vec!["H", "hB"]),
        ("BL".to_string(), vec!["H", "hB"]),
        ("BR".to_string(), vec!["H", "hB"]),
        ("CG".to_string(), vec!["H", "hB"]),
        ("CI".to_string(), vec!["H", "hB"]),
        ("CV".to_string(), vec!["H", "hB"]),
        ("CW".to_string(), vec!["H", "hB"]),
        ("DE".to_string(), vec!["H", "hB"]),
        ("EE".to_string(), vec!["H", "hB"]),
        ("FR".to_string(), vec!["H", "hB"]),
        ("GA".to_string(), vec!["H", "hB"]),
        ("GF".to_string(), vec!["H", "hB"]),
        ("GN".to_string(), vec!["H", "hB"]),
        ("GP".to_string(), vec!["H", "hB"]),
        ("GW".to_string(), vec!["H", "hB"]),
        ("HR".to_string(), vec!["H", "hB"]),
        ("IL".to_string(), vec!["H", "hB"]),
        ("IT".to_string(), vec!["H", "hB"]),
        ("KZ".to_string(), vec!["H", "hB"]),
        ("MC".to_string(), vec!["H", "hB"]),
        ("MD".to_string(), vec!["H", "hB"]),
        ("MF".to_string(), vec!["H", "hB"]),
        ("MQ".to_string(), vec!["H", "hB"]),
        ("MZ".to_string(), vec!["H", "hB"]),
        ("NC".to_string(), vec!["H", "hB"]),
        ("NL".to_string(), vec!["H", "hB"]),
        ("PM".to_string(), vec!["H", "hB"]),
        ("PT".to_string(), vec!["H", "hB"]),
        ("RE".to_string(), vec!["H", "hB"]),
        ("RO".to_string(), vec!["H", "hB"]),
        ("SI".to_string(), vec!["H", "hB"]),
        ("SR".to_string(), vec!["H", "hB"]),
        ("ST".to_string(), vec!["H", "hB"]),
        ("TG".to_string(), vec!["H", "hB"]),
        ("TR".to_string(), vec!["H", "hB"]),
        ("WF".to_string(), vec!["H", "hB"]),
        ("YT".to_string(), vec!["H", "hB"]),
        ("BD".to_string(), vec!["h", "hB", "H"]),
        ("PK".to_string(), vec!["h", "hB", "H"]),
        ("AZ".to_string(), vec!["H", "hB", "h"]),
        ("BA".to_string(), vec!["H", "hB", "h"]),
        ("BG".to_string(), vec!["H", "hB", "h"]),
        ("CH".to_string(), vec!["H", "hB", "h"]),
        ("GE".to_string(), vec!["H", "hB", "h"]),
        ("LI".to_string(), vec!["H", "hB", "h"]),
        ("ME".to_string(), vec!["H", "hB", "h"]),
        ("RS".to_string(), vec!["H", "hB", "h"]),
        ("UA".to_string(), vec!["H", "hB", "h"]),
        ("UZ".to_string(), vec!["H", "hB", "h"]),
        ("XK".to_string(), vec!["H", "hB", "h"]),
        ("AG".to_string(), vec!["h", "hb", "H", "hB"]),
        ("AU".to_string(), vec!["h", "hb", "H", "hB"]),
        ("BB".to_string(), vec!["h", "hb", "H", "hB"]),
        ("BM".to_string(), vec!["h", "hb", "H", "hB"]),
        ("BS".to_string(), vec!["h", "hb", "H", "hB"]),
        ("CA".to_string(), vec!["h", "hb", "H", "hB"]),
        ("DM".to_string(), vec!["h", "hb", "H", "hB"]),
        ("en-001".to_string(), vec!["h", "hb", "H", "hB"]),
        ("en-HK".to_string(), vec!["h", "hb", "H", "hB"]),
        ("en-MY".to_string(), vec!["h", "hb", "H", "hB"]),
        ("FJ".to_string(), vec!["h", "hb", "H", "hB"]),
        ("FM".to_string(), vec!["h", "hb", "H", "hB"]),
        ("GD".to_string(), vec!["h", "hb", "H", "hB"]),
        ("GM".to_string(), vec!["h", "hb", "H", "hB"]),
        ("GU".to_string(), vec!["h", "hb", "H", "hB"]),
        ("GY".to_string(), vec!["h", "hb", "H", "hB"]),
        ("JM".to_string(), vec!["h", "hb", "H", "hB"]),
        ("KI".to_string(), vec!["h", "hb", "H", "hB"]),
        ("KN".to_string(), vec!["h", "hb", "H", "hB"]),
        ("KY".to_string(), vec!["h", "hb", "H", "hB"]),
        ("LC".to_string(), vec!["h", "hb", "H", "hB"]),
        ("LR".to_string(), vec!["h", "hb", "H", "hB"]),
        ("MH".to_string(), vec!["h", "hb", "H", "hB"]),
        ("MP".to_string(), vec!["h", "hb", "H", "hB"]),
        ("MW".to_string(), vec!["h", "hb", "H", "hB"]),
        ("NZ".to_string(), vec!["h", "hb", "H", "hB"]),
        ("SB".to_string(), vec!["h", "hb", "H", "hB"]),
        ("SG".to_string(), vec!["h", "hb", "H", "hB"]),
        ("SL".to_string(), vec!["h", "hb", "H", "hB"]),
        ("SS".to_string(), vec!["h", "hb", "H", "hB"]),
        ("SZ".to_string(), vec!["h", "hb", "H", "hB"]),
        ("TC".to_string(), vec!["h", "hb", "H", "hB"]),
        ("TT".to_string(), vec!["h", "hb", "H", "hB"]),
        ("UM".to_string(), vec!["h", "hb", "H", "hB"]),
        ("US".to_string(), vec!["h", "hb", "H", "hB"]),
        ("VC".to_string(), vec!["h", "hb", "H", "hB"]),
        ("VG".to_string(), vec!["h", "hb", "H", "hB"]),
        ("VI".to_string(), vec!["h", "hb", "H", "hB"]),
        ("ZM".to_string(), vec!["h", "hb", "H", "hB"]),
        ("ES".to_string(), vec!["H", "hB", "h", "hb"]),
        ("GQ".to_string(), vec!["H", "hB", "h", "hb"]),
        ("AE".to_string(), vec!["h", "hB", "hb", "H"]),
        ("ar-001".to_string(), vec!["h", "hB", "hb", "H"]),
        ("BH".to_string(), vec!["h", "hB", "hb", "H"]),
        ("DZ".to_string(), vec!["h", "hB", "hb", "H"]),
        ("EG".to_string(), vec!["h", "hB", "hb", "H"]),
        ("EH".to_string(), vec!["h", "hB", "hb", "H"]),
        ("HK".to_string(), vec!["h", "hB", "hb", "H"]),
        ("IQ".to_string(), vec!["h", "hB", "hb", "H"]),
        ("JO".to_string(), vec!["h", "hB", "hb", "H"]),
        ("KW".to_string(), vec!["h", "hB", "hb", "H"]),
        ("LB".to_string(), vec!["h", "hB", "hb", "H"]),
        ("LY".to_string(), vec!["h", "hB", "hb", "H"]),
        ("MO".to_string(), vec!["h", "hB", "hb", "H"]),
        ("MR".to_string(), vec!["h", "hB", "hb", "H"]),
        ("OM".to_string(), vec!["h", "hB", "hb", "H"]),
        ("PH".to_string(), vec!["h", "hB", "hb", "H"]),
        ("PS".to_string(), vec!["h", "hB", "hb", "H"]),
        ("QA".to_string(), vec!["h", "hB", "hb", "H"]),
        ("SA".to_string(), vec!["h", "hB", "hb", "H"]),
        ("SD".to_string(), vec!["h", "hB", "hb", "H"]),
        ("SY".to_string(), vec!["h", "hB", "hb", "H"]),
        ("TN".to_string(), vec!["h", "hB", "hb", "H"]),
        ("YE".to_string(), vec!["h", "hB", "hb", "H"]),
        ("AF".to_string(), vec!["H", "hb", "hB", "h"]),
        ("LA".to_string(), vec!["H", "hb", "hB", "h"]),
        ("CN".to_string(), vec!["H", "hB", "hb", "h"]),
        ("LV".to_string(), vec!["H", "hB", "hb", "h"]),
        ("TL".to_string(), vec!["H", "hB", "hb", "h"]),
        ("zu-ZA".to_string(), vec!["H", "hB", "hb", "h"]),
        ("JP".to_string(), vec!["H", "K", "h"]),
        ("CD".to_string(), vec!["hB", "H"]),
        ("IR".to_string(), vec!["hB", "H"]),
        ("hi-IN".to_string(), vec!["hB", "h", "H"]),
        ("kn-IN".to_string(), vec!["hB", "h", "H"]),
        ("ml-IN".to_string(), vec!["hB", "h", "H"]),
        ("te-IN".to_string(), vec!["hB", "h", "H"]),
        ("KH".to_string(), vec!["hB", "h", "H", "hb"]),
        ("ta-IN".to_string(), vec!["hB", "h", "hb", "H"]),
        ("BN".to_string(), vec!["hb", "hB", "h", "H"]),
        ("MY".to_string(), vec!["hb", "hB", "h", "H"]),
        ("ET".to_string(), vec!["hB", "hb", "h", "H"]),
        ("gu-IN".to_string(), vec!["hB", "hb", "h", "H"]),
        ("mr-IN".to_string(), vec!["hB", "hb", "h", "H"]),
        ("pa-IN".to_string(), vec!["hB", "hb", "h", "H"]),
        ("TW".to_string(), vec!["hB", "hb", "h", "H"]),
        ("KE".to_string(), vec!["hB", "hb", "H", "h"]),
        ("MM".to_string(), vec!["hB", "hb", "H", "h"]),
        ("TZ".to_string(), vec!["hB", "hb", "H", "h"]),
        ("UG".to_string(), vec!["hB", "hb", "H", "h"])
    ])
});
