[workspace]
members = [
  "icu-messageformat-parser",
  "swc-formatjs-visitor",
  "swc-plugin-formatjs",
  # TODO: add this back. It currently depends on swc_core that is mutually exclusive with
  # swc_core used by the plugin.
  # "swc-formatjs-custom-transform"
]

[profile.release]
lto = true
