#!/usr/bin/env bash
# Generates dist package registries from Bazel query.
# Usage: bash scripts/generate_dist_packages.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$REPO_ROOT/tools/dist_packages_registry.bzl"
LINK_DEPS_OUTPUT="$REPO_ROOT/tools/workspace_package_link_deps.bzl"

TARGETS=$(bazel query 'kind("npm_package rule", //packages/...)' 2>/dev/null \
  | grep -v '^//packages/generated/' \
  | grep ':pkg$' \
  | while read -r target; do
    build=$(bazel query --output=build "$target" 2>/dev/null)
    package_json=$(echo "$build" | grep -o '"//packages/[^"]*:\(package_json\|generated_package_json\)"' | head -n 1 | tr -d '"' || true)
    if [ -z "$package_json" ]; then
      echo "No generated package.json label found for $target" >&2
      exit 1
    fi
    package_name=$(echo "$build" | grep -o 'package = "[^"]*"' | head -n 1 | cut -d '"' -f 2 || true)
    if [ -z "$package_name" ]; then
      echo "No npm package name found for $target" >&2
      exit 1
    fi
    metadata_name="${package_json##*:}_metadata"
    metadata_target="${package_json%:*}:$metadata_name"
    metadata_deps=$(bazel query --output=build "$metadata_target" 2>/dev/null | node -e '
const fs = require("fs")
const input = fs.readFileSync(0, "utf8")
const match = input.match(/content = "((?:\\.|[^"\\])*)"/s)
if (!match) process.exit(0)
const metadata = JSON.parse(JSON.parse(`"${match[1]}"`))
const deps = new Set([
  ...(metadata.dependencies || []),
  ...(metadata.peerDependencies || []),
  ...(metadata.optionalDependencies || []),
])
const workspaceDeps = metadata.workspaceDependencies || []
process.stdout.write(
  `${[...deps].sort().join(",")}|${workspaceDeps.join(",")}`
)
')
    IFS='|' read -r package_deps workspace_deps <<< "$metadata_deps"
    package_store_deps=""
    if [ -n "$package_deps" ]; then
      IFS=',' read -ra package_dep_array <<< "$package_deps"
      IFS=',' read -ra workspace_dep_array <<< "$workspace_deps"
      sep=""
      for package_dep in "${package_dep_array[@]}"; do
        package_store_dep=""
        for workspace_dep in "${workspace_dep_array[@]}"; do
          if [ "$package_dep" = "$workspace_dep" ]; then
            package_store_dep="//:.aspect_rules_js/node_modules/$package_dep"
            break
          fi
        done
        if [ -z "$package_store_dep" ]; then
          dep_build=$(bazel query --output=build "//:node_modules/$package_dep" 2>/dev/null || true)
          package_store_dep=$(echo "$dep_build" | grep -o 'src = "[^"]*"' | head -n 1 | cut -d '"' -f 2 || true)
          if [ -z "$package_store_dep" ]; then
            echo "No npm package store label found for $package_dep required by $target" >&2
            exit 1
          fi
        fi
        package_store_deps+="$sep$package_store_dep=$package_dep"
        sep=","
      done
    fi
    release_deps=$(bazel query "deps($target)" 2>/dev/null \
      | sed -nE 's#^//(crates/[^:]+):.*#\1#p' \
      | sort -u \
      | paste -sd, -)

    package_dir="${target#//packages/}"
    package_dir="${package_dir%:pkg}"
    echo "$package_dir|$target|$package_json|$package_name|$release_deps|$workspace_deps|$package_store_deps"
  done | sort)

DIST_TARGETS=$(echo "$TARGETS" | grep -v '^cli-native-win32-x64|' || true)

cat > "$OUTPUT" << 'HEADER'
# @generated by scripts/generate_dist_packages.sh - DO NOT EDIT
# To regenerate: bash scripts/generate_dist_packages.sh

HEADER

emit_packages() {
  local name=$1
  local targets=$2

  echo "$name = [" >> "$OUTPUT"
  if [ -n "$targets" ]; then
    echo "$targets" | while IFS='|' read -r package_dir target package_json package_name release_deps workspace_deps package_store_deps; do
      release_deps_field=""
      if [ -n "$release_deps" ]; then
        release_deps_field=", \"release_deps\": ["
        sep=""
        IFS=',' read -ra release_dep_array <<< "$release_deps"
        for release_dep in "${release_dep_array[@]}"; do
          release_deps_field+="$sep\"$release_dep\""
          sep=", "
        done
        release_deps_field+="]"
      fi
      workspace_deps_field=""
      if [ -n "$workspace_deps" ]; then
        workspace_deps_field=", \"workspace_deps\": ["
        sep=""
        IFS=',' read -ra workspace_dep_array <<< "$workspace_deps"
        for workspace_dep in "${workspace_dep_array[@]}"; do
          workspace_deps_field+="$sep\"$workspace_dep\""
          sep=", "
        done
        workspace_deps_field+="]"
      fi
      echo "    {\"dirname\": \"$package_dir\", \"name\": \"$package_name\", \"pkg\": \"$target\", \"package_json\": \"$package_json\"$release_deps_field$workspace_deps_field}," >> "$OUTPUT"
    done
  fi
  echo "]" >> "$OUTPUT"
}

emit_packages "DIST_PACKAGES" "$DIST_TARGETS"

echo >> "$OUTPUT"

emit_packages "RELEASE_PLEASE_NPM_PACKAGES" "$TARGETS"

echo "Generated $OUTPUT"

cat > "$LINK_DEPS_OUTPUT" << 'HEADER'
# @generated by scripts/generate_dist_packages.sh - DO NOT EDIT
# To regenerate: bash scripts/generate_dist_packages.sh

WORKSPACE_PACKAGE_LINK_DEPS = {
HEADER

if [ -n "$TARGETS" ]; then
  echo "$TARGETS" | while IFS='|' read -r package_dir target package_json package_name release_deps workspace_deps package_store_deps; do
    if [ -z "$package_store_deps" ]; then
      continue
    fi
    echo "    \"$package_name\": {" >> "$LINK_DEPS_OUTPUT"
    IFS=',' read -ra package_store_dep_array <<< "$package_store_deps"
    for package_store_dep in "${package_store_dep_array[@]}"; do
      package_store_dep_label="${package_store_dep%%=*}"
      package_store_dep_name="${package_store_dep#*=}"
      echo "        \"$package_store_dep_label\": \"$package_store_dep_name\"," >> "$LINK_DEPS_OUTPUT"
    done
    echo "    }," >> "$LINK_DEPS_OUTPUT"
  done
fi

echo "}" >> "$LINK_DEPS_OUTPUT"

echo "Generated $LINK_DEPS_OUTPUT"
