#!/usr/bin/env bash
# Generates tools/dist_packages_registry.bzl from Bazel query.
# Usage: bash scripts/generate_dist_packages.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$REPO_ROOT/tools/dist_packages_registry.bzl"

TARGETS=$(bazel query 'kind("npm_package rule", //packages/...)' 2>/dev/null \
  | grep -v '^//packages/generated/' \
  | grep ':pkg$' \
  | while read -r target; do
    build=$(bazel query --output=build "$target" 2>/dev/null)
    package_json=$(echo "$build" | grep -o '"//packages/[^"]*:\(package\.json\|package_json\|generated_package_json\)"' | head -n 1 | tr -d '"' || true)
    if [ -z "$package_json" ]; then
      echo "No package.json label found for $target" >&2
      exit 1
    fi
    package_name=$(echo "$build" | grep -o 'package = "[^"]*"' | head -n 1 | cut -d '"' -f 2 || true)
    if [ -z "$package_name" ]; then
      echo "No npm package name found for $target" >&2
      exit 1
    fi
    release_deps=$(bazel query "deps($target)" 2>/dev/null \
      | sed -nE 's#^//(crates/[^:]+):.*#\1#p' \
      | sort -u \
      | paste -sd, -)

    package_dir="${target#//packages/}"
    package_dir="${package_dir%:pkg}"
    echo "$package_dir|$target|$package_json|$package_name|$release_deps"
  done | sort)

DIST_TARGETS=$(echo "$TARGETS" | grep -v '^cli-native-win32-x64|' || true)

cat > "$OUTPUT" << 'HEADER'
# @generated by scripts/generate_dist_packages.sh - DO NOT EDIT
# To regenerate: bash scripts/generate_dist_packages.sh

HEADER

emit_packages() {
  local name=$1
  local targets=$2

  echo "$name = [" >> "$OUTPUT"
  if [ -n "$targets" ]; then
    echo "$targets" | while IFS='|' read -r package_dir target package_json package_name release_deps; do
      release_deps_field=""
      if [ -n "$release_deps" ]; then
        release_deps_field=", \"release_deps\": ["
        sep=""
        IFS=',' read -ra release_dep_array <<< "$release_deps"
        for release_dep in "${release_dep_array[@]}"; do
          release_deps_field+="$sep\"$release_dep\""
          sep=", "
        done
        release_deps_field+="]"
      fi
      echo "    {\"dirname\": \"$package_dir\", \"name\": \"$package_name\", \"pkg\": \"$target\", \"package_json\": \"$package_json\"$release_deps_field}," >> "$OUTPUT"
    done
  fi
  echo "]" >> "$OUTPUT"
}

emit_packages "DIST_PACKAGES" "$DIST_TARGETS"

echo >> "$OUTPUT"

emit_packages "RELEASE_PLEASE_NPM_PACKAGES" "$TARGETS"

echo "Generated $OUTPUT"
