#!/usr/bin/env bash
# Generates tools/generated_packages_registry.bzl from Bazel query.
# Usage: bazel run //:generate-generated-packages
#   or:  ./scripts/generate_generated_packages.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$REPO_ROOT/tools/generated_packages_registry.bzl"

# Find all formatjs_generated_package targets (they create npm_package with @formatjs_generated scope)
TARGETS=$(bazel query 'kind("npm_package rule", //...)' 2>/dev/null \
  | grep -v '//:node_modules' \
  | while read -r target; do
    # Check if this npm_package has @formatjs_generated in its package attr
    pkg_attr=$(bazel query --output=build "$target" 2>/dev/null | grep -o '"@formatjs_generated/[^"]*"' || true)
    if [ -n "$pkg_attr" ]; then
      # Extract package name (strip quotes and scope)
      name=$(echo "$pkg_attr" | sed 's/"@formatjs_generated\///' | sed 's/"//')
      echo "$name|$target"
    fi
  done | sort)

cat > "$OUTPUT" << 'HEADER'
# @generated by scripts/generate_generated_packages.sh — DO NOT EDIT
# To regenerate: bazel run //:generate-generated-packages

HEADER

echo "GENERATED_PACKAGES = [" >> "$OUTPUT"

if [ -n "$TARGETS" ]; then
  echo "$TARGETS" | while IFS='|' read -r name target; do
    echo "    {\"name\": \"$name\", \"target\": \"$target\"}," >> "$OUTPUT"
  done
fi

echo "]" >> "$OUTPUT"

echo "Generated $OUTPUT"
