load("@rules_rs//rs:rust_proc_macro.bzl", "rust_proc_macro")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

exports_files(
    [
        "Cargo.toml",
        "lib.rs",
    ],
    visibility = ["//visibility:public"],
)

rust_proc_macro(
    name = "formatjs_intl_macros",
    srcs = ["lib.rs"],
    crate_name = "formatjs_intl_macros",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/icu_messageformat_parser",
        "@crates//:base64",
        "@crates//:quote",
        "@crates//:sha2",
        "@crates//:syn",
    ],
)

rust_test(
    name = "formatjs_intl_macros_test",
    size = "small",
    crate = ":formatjs_intl_macros",
)
