from typing import Any, Mapping

MessageValue = str | bool | int | float | None

class IcuMessageFormat:
    def __init__(self, message: str, *, locale: str = "en") -> None: ...
    def format(self, values: Mapping[str, MessageValue] | None = None) -> str: ...
    def get_ast(self) -> list[dict[str, Any]]: ...
