load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

exports_files(
    [
        "Cargo.toml",
        "README.md",
        "error.rs",
        "formatter.rs",
        "lib.rs",
        "provider_tests.rs",
        "value.rs",
    ],
    visibility = ["//visibility:public"],
)

rust_library(
    name = "icu_messageformat",
    srcs = [
        "error.rs",
        "formatter.rs",
        "lib.rs",
        "provider_tests.rs",
        "value.rs",
    ],
    crate_features = ["compiled_data"],
    crate_name = "formatjs_icu_messageformat",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/icu_messageformat_parser",
        "//crates/icu_skeleton_parser",
        "@crates//:fixed_decimal",
        "@crates//:icu",
        "@crates//:icu_provider",
    ],
)

rust_test(
    name = "icu_messageformat_test",
    size = "small",
    compile_data = ["testdata/fr_pl.postcard"],
    crate = ":icu_messageformat",
    crate_features = ["compiled_data"],
    deps = ["@crates//:icu_provider_blob"],
)

rust_library(
    name = "without_compiled_data",
    testonly = True,
    srcs = [
        "error.rs",
        "formatter.rs",
        "lib.rs",
        "provider_tests.rs",
        "value.rs",
    ],
    crate_name = "formatjs_icu_messageformat",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/icu_messageformat_parser",
        "//crates/icu_skeleton_parser",
        "@crates//:fixed_decimal",
        "@crates//:icu",
        "@crates//:icu_provider",
    ],
)

rust_test(
    name = "provider_test",
    size = "small",
    compile_data = ["testdata/fr_pl.postcard"],
    crate = ":without_compiled_data",
    deps = ["@crates//:icu_provider_blob"],
)
