# @generated by scripts/generate_generated_packages.sh — DO NOT EDIT
# To regenerate: ./scripts/generate_generated_packages.sh

GENERATED_PACKAGES = [
    {"name": "cldr.core", "target": "//packages/intl-getcanonicallocales:cldr_core_pkg"},
    {"name": "cldr.locale", "target": "//packages/intl-locale:cldr_locale_pkg"},
    {"name": "cldr.number", "target": "//packages/intl-numberformat:cldr_number_pkg"},
    {"name": "tz", "target": "//packages/intl-datetimeformat:tz_pkg"},
]
