import {dirname, join} from 'path'
import {createRequire} from 'node:module'
import {readFileSync} from 'fs'
import {outputFileSync} from 'fs-extra/esm'
import glob from 'fast-glob'
import minimist from 'minimist'

const require = createRequire(import.meta.url)

interface Args extends minimist.ParsedArgs {
  baseDir?: string
  cldrPackage: string
  glob: string | string[]
  jsonPath?: string
  out: string
  variable?: string
}

function asArray<T>(value: T | T[] | undefined): T[] {
  if (value === undefined) {
    return []
  }
  return Array.isArray(value) ? value : [value]
}

function isCanonicalLocale(locale: string): boolean {
  try {
    return Intl.getCanonicalLocales(locale).length > 0
  } catch {
    return false
  }
}

function getPackageRoot(cldrPackage: string): string {
  return dirname(require.resolve(`${cldrPackage}/package.json`))
}

function getPathValue(value: unknown, path: string): unknown {
  return path.split('.').reduce((current, segment) => {
    if (current && typeof current === 'object' && segment in current) {
      return (current as Record<string, unknown>)[segment]
    }
    throw new Error(`Unable to resolve JSON path "${path}"`)
  }, value)
}

function getLocalesFromFiles(files: string[]): string[] {
  return files.map(file => file.split(/[\\/]/)[0]).filter(isCanonicalLocale)
}

function getLocalesFromJson(root: string, files: string[], jsonPath: string) {
  return files.flatMap(file => {
    const json = JSON.parse(readFileSync(join(root, file), 'utf8'))
    const value = getPathValue(json, jsonPath)
    if (!value || typeof value !== 'object' || Array.isArray(value)) {
      throw new Error(`JSON path "${jsonPath}" must resolve to an object`)
    }
    return Object.keys(value).filter(isCanonicalLocale)
  })
}

function formatLocales(variable: string, locales: string[]): string {
  const lines = [
    '# Generated by //tools:generate-cldr-locales. Do not edit manually.',
    `${variable} = [`,
    ...locales.map(locale => `    "${locale}",`),
    ']',
    '',
  ]
  return lines.join('\n')
}

function main(args: Args) {
  const {cldrPackage, jsonPath, out, variable = 'ALL_LOCALES'} = args
  const patterns = asArray(args.glob)

  if (!cldrPackage) {
    throw new Error('--cldrPackage is required')
  }
  if (!out) {
    throw new Error('--out is required')
  }
  if (!patterns.length) {
    throw new Error('--glob is required')
  }

  const packageRoot = getPackageRoot(cldrPackage)
  const root = args.baseDir ? join(packageRoot, args.baseDir) : packageRoot
  const files = glob.sync(patterns, {cwd: root, onlyFiles: true}).sort()
  const locales = new Set(
    jsonPath
      ? getLocalesFromJson(root, files, jsonPath)
      : getLocalesFromFiles(files)
  )

  outputFileSync(out, formatLocales(variable, [...locales].sort()))
}

if (import.meta.filename === process.argv[1]) {
  main(minimist<Args>(process.argv.slice(2)))
}
