# @generated by scripts/generate_generated_packages.sh — DO NOT EDIT
# To regenerate: bazel run //:generate-generated-packages

GENERATED_PACKAGES = [
    {"name": "cldr.core", "target": "//packages/intl-getcanonicallocales:cldr_core_pkg"},
    {"name": "cldr.locale", "target": "//packages/intl-locale:cldr_locale_pkg"},
    {"name": "cldr.number", "target": "//packages/intl-numberformat:cldr_number_pkg"},
    {"name": "cldr.supported-locales", "target": "//packages/intl-datetimeformat:cldr_sl_pkg"},
    {"name": "cldr.supported-values", "target": "//packages/intl-supportedvaluesof:cldr_sv_pkg"},
]
