"Custom macro"

load("@aspect_bazel_lib//lib:copy_to_bin.bzl", "copy_to_bin")
load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_library", "js_run_binary")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@npm//:@typescript/native-preview/package_json.bzl", tsgo_bin = "bin")
load("//tools:oxc_transpiler.bzl", "oxc_transpiler")
load("//tools:tsconfig.bzl", "BASE_NODE_TSCONFIG", "BASE_TSCONFIG", "ESNEXT_TSCONFIG")

def ts_compile_node(name, srcs, deps = [], data = [], visibility = None):
    """Compile TS with prefilled args, specifically for Node tooling.

    Args:
        name: target name
        srcs: src files
        deps: deps
        data: add data deps like internal transitive deps
        visibility: visibility
    """

    # Type check only with tsgo (fast, parallel)
    ts_project(
        name = "%s-esm-esnext-typecheck" % name,
        srcs = srcs,
        declaration = True,
        tsconfig = ESNEXT_TSCONFIG,
        resolve_json_module = True,
        deps = deps,
        transpiler = tsgo_bin.tsgo,
        no_emit = True,
    )

    # Transpile with oxc-transform (fast JS and .d.ts generation)
    ts_project(
        name = "%s-esm-esnext" % name,
        srcs = srcs,
        declaration = True,
        tsconfig = ESNEXT_TSCONFIG,
        resolve_json_module = True,
        deps = deps + ["//:node_modules/oxc-transform"],
        transpiler = oxc_transpiler,
        declaration_transpiler = oxc_transpiler,
    )

    js_library(
        name = name,
        srcs = [":%s-esm-esnext" % name, "package.json"],
        data = data,
        visibility = visibility,
    )

def ts_compile(name, srcs, deps = [], visibility = None, tsconfig = None):
    """Compile TS with prefilled args.

    Args:
        name: target name
        srcs: src files
        deps: deps
        visibility: visibility
        tsconfig: optional tsconfig dict override (defaults to BASE_TSCONFIG)
    """

    effective_tsconfig = tsconfig or BASE_TSCONFIG

    # Always build ESM bundle
    # Type check only with tsgo (fast, parallel)
    ts_project(
        name = "%s-esm-typecheck" % name,
        srcs = srcs,
        declaration = True,
        tsconfig = effective_tsconfig,
        resolve_json_module = True,
        deps = deps,
        transpiler = tsgo_bin.tsgo,
        no_emit = True,
    )

    # Transpile with oxc-transform (fast JS and .d.ts generation)
    ts_project(
        name = "%s-esm" % name,
        srcs = srcs,
        declaration = True,
        tsconfig = effective_tsconfig,
        resolve_json_module = True,
        deps = deps + ["//:node_modules/oxc-transform"],
        transpiler = oxc_transpiler,
        declaration_transpiler = oxc_transpiler,
    )

    js_library(
        name = name,
        srcs = [":%s-esm" % name, "package.json"],
        visibility = visibility,
    )

def ts_binary(name, data = [], node_options = [], **kwargs):
    """Create a TS binary with prefilled args.

    Args:
        name: target name
        data: data files or dependencies
        node_options: additional Node.js options
        **kwargs: additional arguments passed to js_binary
    """
    js_binary(
        name = name,
        data = data,
        node_options = node_options + [
            "--experimental-transform-types",
        ],
        **kwargs
    )

def ts_run_binary(name, entry_point = None, args = [], tool = None, chdir = None, srcs = [], outs = [], out_dirs = [], **kwargs):
    """Runs a TypeScript binary, optionally creating the tool if not provided.

    Args:
        name: target name
        entry_point: entry point script for the binary
        args: arguments to pass to the binary
        tool: tool binary label (optional)
        chdir: working directory to run the binary in (optional)
        srcs: source files required by the binary
        outs: output files generated by the binary
        out_dirs: output directories generated by the binary
        **kwargs: additional arguments passed to js_run_binary
    """
    if not tool and not entry_point:
        fail("Either tool or entry_point must be provided to ts_run_binary")
    if not tool:
        ts_binary(
            name = "%s_tool" % name,
            entry_point = entry_point,
            chdir = chdir,
        )
    js_run_binary(
        name = name,
        tool = tool if tool else ":%s_tool" % name,
        chdir = chdir,
        srcs = srcs,
        outs = outs,
        out_dirs = out_dirs,
        args = args,
        **kwargs
    )

def generate_src_file(name, src, entry_point = None, tool = None, chdir = None, args = [], data = [], visibility = [], tags = []):
    """Generate a source file.

    Args:
        name: target name
        args: args to generate src file binary
        data: dependent data labels
        src: src file to generate
        entry_point: generation script entry point
        visibility: target visibility
        chdir: whether to chdir to another dir
        tool: tool binary label
        tags: tags to apply to the target
    """
    file_ext = src[src.rindex(".") + 1:]
    tmp_filename = "%s.tmp.%s" % (name, file_ext)

    # File extensions supported by oxfmt
    oxfmt_extensions = [
        "js",
        "jsx",
        "ts",
        "tsx",
        "mjs",
        "cjs",
        "mts",
        "cts",
        "vue",
        "html",
        "mjml",
        "css",
        "scss",
        "less",
        "md",
        "mdx",
        "graphql",
        "gql",
        "yaml",
        "yml",
        "toml",
        "json",
        "jsonc",
        "json5",
    ]

    ts_run_binary(
        name = tmp_filename[:tmp_filename.rindex(".")],
        outs = [tmp_filename],
        entry_point = entry_point,
        tool = tool,
        # NOTE: assumes that all scripts called here accept `--out` and
        # also uses fs-extra + minimist.
        args = args + [
            "--out",
            "$(rootpath %s)" % tmp_filename,
        ],
        chdir = chdir,
        srcs = data + [
            "//:node_modules/fs-extra",
            "//:node_modules/minimist",
        ],
    )

    # Format the generated file if oxfmt supports this file type
    if file_ext in oxfmt_extensions:
        formatted_filename = "%s.formatted.%s" % (name, file_ext)
        native.genrule(
            name = "%s_format" % name,
            srcs = [tmp_filename],
            outs = [formatted_filename],
            cmd = "cat $(location %s) | $(location //:oxfmt) --stdin-filepath=$(location %s) > $@" % (tmp_filename, tmp_filename),
            tools = ["//:oxfmt"],
        )
        final_file = formatted_filename
    else:
        final_file = tmp_filename

    files = {}
    files[src] = final_file

    write_source_files(
        name = name,
        files = files,
        visibility = visibility + [
            "//:__pkg__",
        ],
        suggested_update_target = "//%s:%s" % (native.package_name(), tmp_filename[:tmp_filename.rindex(".")]),
        tags = tags + ["codegen"],
    )

def generate_ide_tsconfig_json(name = "tsconfig_json"):
    """Generate a tsconfig.json file with the correct extends path based on package depth.

    This macro calculates the correct relative path to the root tsconfig.json
    based on the package's location in the repository.

    Args:
        name: target name (default: "tsconfig_json")
    """
    package = native.package_name()

    # Calculate depth: count number of directory levels
    # Empty string (root) = 0, "docs" = 1, "packages/foo" = 2
    depth = len(package.split("/")) if package else 0

    # Generate the extends path: one "../" per level to reach root
    # For packages/foo (depth=2): ../../tsconfig.json
    # For docs (depth=1): ../tsconfig.json
    extends_path = ("../" * depth) + "tsconfig.json"

    # Create tsconfig as a dict
    tsconfig = {
        "extends": extends_path,
    }

    # Encode to JSON
    json_content = json.encode_indent(tsconfig, indent = "  ")

    # Add comment header
    content = "// @generated\n{\n  // This is purely for IDE, not for compilation\n  \"extends\": \"%s\"\n}\n" % extends_path

    native.genrule(
        name = name + "_generated",
        outs = [name + ".generated.json"],
        cmd = "printf '%s' > $@" % content,
    )

    write_source_files(
        name = name,
        files = {"tsconfig.json": name + "_generated"},
    )

def generate_package_json(
        name = "package_json",
        package_name = None,
        version = "0.0.0",
        description = "",
        exports = {".": "./index.js"},
        dependencies = {},
        dev_dependencies = {},
        peer_dependencies = {},
        peer_dependencies_meta = {},
        keywords = [],
        sideEffects = None,
        main = None,
        contributors = [],
        extra = {}):
    """Generate a package.json file from BUILD.bazel metadata.

    Args:
        name: target name (default: "package_json")
        package_name: npm package name (e.g. "@formatjs/ecma402-abstract")
        version: package version
        description: package description
        exports: exports map
        dependencies: production dependencies dict
        dev_dependencies: dev dependencies dict
        peer_dependencies: peer dependencies dict
        peer_dependencies_meta: peer dependencies meta dict
        keywords: list of keywords
        sideEffects: whether the package has side effects (None to omit)
        main: main entry point (None to omit)
        contributors: list of contributor strings
        extra: additional fields to merge into the package.json
    """
    if not package_name:
        fail("package_name is required for generate_package_json")

    pkg = {}
    pkg["name"] = package_name
    pkg["description"] = description
    pkg["version"] = version
    pkg["license"] = "MIT"
    pkg["author"] = "Long Ho <holevietlong@gmail.com>"
    pkg["type"] = "module"

    if sideEffects != None:
        pkg["sideEffects"] = sideEffects

    pkg["types"] = "index.d.ts"

    if exports:
        pkg["exports"] = exports

    if dependencies:
        pkg["dependencies"] = dependencies

    if dev_dependencies:
        pkg["devDependencies"] = dev_dependencies

    if peer_dependencies:
        pkg["peerDependencies"] = peer_dependencies

    pkg["bugs"] = "https://github.com/formatjs/formatjs/issues"

    if contributors:
        pkg["contributors"] = contributors

    pkg["homepage"] = "https://github.com/formatjs/formatjs"

    if keywords:
        pkg["keywords"] = keywords

    if main:
        pkg["main"] = main

    if peer_dependencies_meta:
        pkg["peerDependenciesMeta"] = peer_dependencies_meta

    pkg["repository"] = "formatjs/formatjs.git"

    # Merge extra fields
    for k, v in extra.items():
        pkg[k] = v

    content = json.encode_indent(pkg, indent = "  ")

    native.genrule(
        name = name + "_generated",
        outs = [name + ".generated.json"],
        cmd = "cat > $@ << 'EOF'\n%s\nEOF" % content,
    )

    write_source_files(
        name = name,
        files = {"package.json": name + "_generated"},
    )

def is_internal_dep(s):
    return s.startswith("//:node_modules/@formatjs") or s in [
        "//:node_modules/babel-plugin-formatjs",
        "//:node_modules/eslint-plugin-formatjs",
        "//:node_modules/intl-messageformat",
        "//:node_modules/react-intl",
        "//:node_modules/vue-intl",
        "//:node_modules/@formatjs/svelte-intl",
    ]

def package_json_test(name, packageJson = "package.json", deps = []):
    copy_to_bin(
        name = "package",
        srcs = ["package.json"],
        visibility = ["//visibility:public"],
    )

    internal_deps = [
        s
        for s in deps
        if is_internal_dep(s)
    ]

    external_deps = [s for s in deps if s not in internal_deps]

    # TODO: fix this
    # ts_node_bin.ts_node_test(
    #     name = name,
    #     args = [
    #                "--transpile-only",
    #                "$(location //tools:check-package-json)",
    #                "--rootPackageJson",
    #                "$(location //:package)",
    #                "--packageJson",
    #                "$(location %s)" % packageJson,
    #            ] +
    #            (["--externalDep %s" % n for n in external_deps] if external_deps else []) +
    #            (["--internalDep %s" % d.split("//:node_modules/")[1] for d in internal_deps] if internal_deps else []),
    #     data = internal_deps + [
    #         packageJson,
    #         "//tools:check-package-json",
    #         "//:package",
    #         "//:tsconfig",
    #         "//:node_modules/@types/fs-extra",
    #         "//:node_modules/@types/minimist",
    #         "//:node_modules/fs-extra",
    #         "//:node_modules/json-stable-stringify",
    #
    #         "//:node_modules/minimist",
    #         "//:node_modules/lodash",
    #         "//:node_modules/@types/lodash",
    #         "//:node_modules/unidiff",
    #         "//:node_modules/tslib",
    #         "//:tsconfig.node",
    #     ],
    # )
