"""Package.json formatting policy."""

PACKAGE_JSON_SORT_FIRST = [
    "name",
    "version",
    "private",
    "description",
    "keywords",
    "homepage",
    "bugs",
    "license",
    "author",
    "contributors",
    "repository",
    "files",
    "bin",
    "os",
    "cpu",
    "libc",
    "type",
    "sideEffects",
    "main",
    "source",
    "types",
    "exports",
    "imports",
    "scripts",
    "dependencies",
    "peerDependencies",
    "peerDependenciesMeta",
    "optionalDependencies",
    "engines",
    "browserslist",
    "alias",
]

PACKAGE_JSON_SORT_EXPORTS = [
    "types",
    "node-addons",
    "edge-light",
    "node",
    "browser",
    "import",
    "require",
    "development",
    "production",
    "default",
]
