# # load("@npm//@docusaurus/core:index.bzl", "docusaurus")
# load("@build_bazel_rules_nodejs//:index.bzl", "nodejs_binary")

# nodejs_binary(
#     name = "build",
#     data = glob([
#         "src/**/*",
#         "docs/**/*",
#         "lang/**/*",
#         "static/**/*",
#     ]) + [
#         "build.js",
#         "docusaurus.config.js",
#         "sidebars.js",
#         "package.json",
#         "@npm//fs-extra",
#         "@npm//react",
#         "@npm//react-dom",
#         "@npm//classnames",
#         "@npm//@docusaurus/core",
#         "@npm//@docusaurus/preset-classic",
#         "//packages/react-intl:dist",
#     ],
#     entry_point = "build.js",
#     templated_args = [
#         "--out-dir",
#     ],
# )
# # docusaurus(
# #     name = "build",
# #     args = [
# #         "build",
# #         "--node_options=--require=./$(rootpath chdir.js)",
# #     ],
# #     # entry_point="@npm//:node_modules/@docusaurus/core/bin/docusaurus.js",
# #     data = glob([
# #         "src/**/*",
# #         "docs/**/*",
# #         "lang/**/*",
# #         "static/**/*",
# #     ]) + [
# #         "chdir.js",
# #         "docusaurus.config.js",
# #         "sidebars.js",
# #         "package.json",
# #         "@npm//fs-extra",
# #         "@npm//react",
# #         "@npm//react-dom",
# #         "@npm//classnames",
# #         "@npm//@docusaurus/preset-classic",
# #         "//packages/react-intl:dist",
# #     ],
# #     output_dir = True,
# # )

# # alias(
# #     name="deploy",
# #     actual=".docusaurus"
# # )
