[package]
authors     = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "formatjs plugin for SWC"
edition     = "2021"
license     = "MIT"
name        = "swc-plugin-formatjs"
repository  = "https://github.com/kwonoj/swc-plugin-formatjs"
version     = "0.0.2"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
serde_json = "1"
swc-formatjs-visitor = { path = "../swc-formatjs-visitor", version = "0.0.2", features = [
  "plugin",
] }
swc_core = { version = "0.23.13", features = ["plugin_transform"] }
