name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: bazelbuild/setup-bazelisk@v3

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: '~/.cache/bazel'
          key: bazel-${{ matrix.os }}

      - name: Run tests
        env:
          # Only set BuildBuddy API key for internal PRs and pushes
          BUILDBUDDY_API_KEY: ${{ (github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push') && secrets.BUILDBUDDY_ORG_API_KEY || '' }}
        run: |
          if [ -n "$BUILDBUDDY_API_KEY" ]; then
            bazel test \
              --config=ci \
              --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY \
              //...
          else
            bazel test \
              --config=ci \
              --noremote_upload_local_results \
              //...
          fi
